version: '3.8'

services:
  backend:
    build: ./backend/deploy
    networks:
      - backend_network
    expose:
      - "8000"  # Exposes the port to other containers but not to the outside world.
    # depends_on:
    #   - db
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=mydb
    #   - DB_USER=user
    #   - DB_PASSWORD=password
    # env_file:
    #   - .env

  frontend:
    build: ./frontend/deploy
    networks:
      - frontend_network
    ports:
      - "80:3000"  # Exposes React on port 80 (public access)
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Backend API URL (communicates via Docker network)

  nginx:
    image: nginx:alpine
    networks:
      - frontend_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Exposes Nginx on port 80
    depends_on:
      - frontend
      - backend

  # does not exist for now
  # db:
  #   image: postgres:13
  #   networks:
  #     - backend_network
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  postgres_data:
