services:
  backend:
    build: 
      context: ./backend
      dockerfile: deploy/Dockerfile
    networks:
      - backend_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: deploy/Dockerfile
    networks:
      - frontend_network
    ports:
      - "3000:3000"  # Exposes React on port 80 (public access)
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Backend API URL (communicates via Docker network)

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  postgres_data:
