services:
  backend:
    build: 
      context: ./backend
      dockerfile: deploy/Dockerfile
    networks:
      - backend_network
    ports:
      - "8000:8000"
    volumes:
      - "~/.aws:/root/.aws"
    working_dir: /backend

  frontend:
    build:
      context: ./frontend
      dockerfile: deploy/Dockerfile
    networks:
      - frontend_network
    ports:
      - "3000:3000"
    working_dir: /frontend
  
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
