services:
  backend:
    build: 
      context: ./backend
      dockerfile: deploy/Dockerfile
    networks:
      - backend_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: deploy/Dockerfile
    networks:
      - frontend_network
    ports:
      - "3000:3000"
  
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
