# Frontend Dockerfile

# Use an official Node runtime as a parent image
FROM node:16-slim

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . /app/

# Expose the port React will run on
EXPOSE 3000

# Run the React development server
CMD ["npm", "start"]
