# Frontend Dockerfile
FROM node:22 AS build

WORKDIR /frontend

COPY ./package*.json /frontend/

RUN npm install

# Copy frontend code
COPY . .

ENV PORT 3000
EXPOSE 3000

# Build React app
CMD ["npm", "start", "0.0.0.0:3000"]
