aws_region      = "us-west-1"
instance_type   = "t2.micro"
ssm_backend_url_key = "/ow_winrate_tracker/backend_url"
ssh_key_name    = "ow_winrate_tracker"
ssm_debug_mode_key = "ow_winrate_tracker/debug_mode"
