# Backend Dockerfile
FROM python:3.11-slim

WORKDIR /backend

COPY ./requirements.txt /backend/

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . /backend/

# Expose the port that the backend will run on
EXPOSE 8000

# TODO Should only be visible to FE not world
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
